---
- name: Download EPEL package
  get_url:
  	url=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  	dest=/tmp/epel-release-latest-7.noarch.rpm
  	mode=0400

- name: Enable EPEL
  command: rpm -Uvh /tmp/epel-release-latest-7.noarch.rpm creates=/etc/yum.repos.d/epel.repo

- name: Install common packages
  yum:
  	name={{ item }}
  	state=latest
  with_items:
  - atool
  - emacs-nox
  - elinks
  - git
  - git-svn
  - htop
  - lsof
  - lynx
  - man
  - mosh
  - mtr
  - nmap
  - ncdu
  - vim
  - rsync
  - screen
  - subversion
  - tmux
  - wget
  - zsh
  - pciutils
  - bind-utils
  - cowsay
  - python-celery
  - libselinux-python
  tags:
  - packages

- name: Install packages for development
  yum:
  	name={{ item }}
  	state=latest
  with_items:
  - gcc
  - gcc-arm-linux-gnu
  - gcc-mips64-linux-gnu
  - gcc-sparc64-linux-gnu
  - gcc-x86_64-linux-gnu
  - make
  - openmpi
  - openmpi-devel
  - ruby
  - autoconf
  - automake
  - bison
  - byacc
  - cscope
  - ctags
  - diffstat
  - doxygen
  - elfutils
  - flex
  - gcc-c++
  - indent
  - intltool
  - libtool
  - patch
  - patchutils
  - rcs
  - redhat-rpm-config
  - rpm-build
  - swig
  - systemtap
  - unzip
  - zip
  tags:
  - packages
