---
- name: Install packages for auth
  yum:
  	name={{ item }}
  	state=latest
  with_items:
  - pam_krb5
  - krb5-libs
  - krb5-workstation
  - nscd
  - sssd
  - openldap
  tags:
  - packages
  - auth

- name: Install LDAP certificate
  copy:
  	src=ldap.vtluug.org.pem
  	dest=/etc/ssl/certs/ldap.vtluug.org.pem
  	mode=0644

- name: Install krb5.conf
  copy:
  	src=krb5.conf
  	dest=/etc/krb5.conf
  	mode=0644

- name: Run authconfig
  command: authconfig --updateall
           --enableshadow --passalgo=sha512 --enablelocauthorize
           --enablekrb5 --disablekrb5kdcdns --disablekrb5realmdns
           --krb5kdc=${krb5_server} --krb5adminserver=${krb5_server}
           --krb5realm=${krb5_realm}
           --enableldap --disableldapauth
           --ldapserver=${ldap_server} --ldapbasedn=${ldap_base}
           --enablecache

- name: Install sssd.conf
  template:
  	src=sssd.conf.j2
  	dest=/etc/sssd/sssd.conf
  	mode=0600
  notify: Restart sssd

- name: Stop unneeded auth services
  service:
  	name=$item
  	state=stopped
  with_items:
  - nscd
  - nslcd

- name: Disable unneeded auth services
  service:
  	name=$item
  	enabled=no
  with_items:
  - nscd
  - nslcd

- name: Enable sssd
  service:
  	name=sssd
  	enabled=yes
