---
ntp_servers:
  - ntp.vt.edu
  - ntp-1.vt.edu
  - ntp-2.vt.edu
  - 0.centos.pool.ntp.org
  - 1.centos.pool.ntp.org
  - 2.centos.pool.ntp.org
root_email: root@vtluug.org
postfix_relayhost: acidburn.vtluug.org
ldap_server: blade.vtluug.org
ldap_base: dc=vtluug,dc=org
ldap_cacert: /etc/ssl/certs/ldap.vtluug.org.pem
krb5_server: blade.vtluug.org
krb5_backup_server: westinghouse.vtluug.org
krb5_kpasswd: blade.vtluug.org
krb5_realm: VTLUUG.ORG
