---
new_vms_meltdown:
#  - { target: meltdown, os: ubuntu-18.04, hostname: sczi,          cpus: 4, ram: 16384, size: 50G, mac: "02:00:0a:62:00:0b", admins: sudo, variant: ubuntu17.10 }  # Web
  - { target: meltdown, os: alma-8.5,   hostname: chimera,       cpus: 2, ram: 2048, size: 10G, mac: "02:00:0a:62:00:0a", admins: wheel, variant: rhel7.5 }   # FreeIPA
  - { target: meltdown, os: alma-8.5,   hostname: sphinx,       cpus: 2, ram: 2048, size: 10G, mac: "02:00:0a:62:00:0d", admins: wheel, variant: rhel7.5 }   # FreeIPA replica, the stable osinfo-db package doesn't have any more fitting variant
  - { target: meltdown, os: ubuntu-18.04, hostname: acidburn,      cpus: 2, ram: 2048, size: 10G, mac: "02:00:0a:62:00:0c", admins: sudo, variant: ubuntu17.10 }  # Shell
  - { target: meltdown, os: debian-12, hostname: nikonwormhole,      cpus: 2, ram: 2048, size: 10G, mac: "02:00:0a:62:00:0e", admins: sudo, variant: ubuntu17.10 }  # dns-adguard
# Add more service VMs here later

new_vms_spectre:
# Add user VMs here later
  - { target: spectre, os: ubuntu-18.04, hostname: scaryterry, cpus: 2, ram: 16384, size: 50G, mac: "02:00:0a:62:00:0f", admins: sudo, variant: ubuntu17.10 } # Web
